apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: api-server
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
    - host: api-server
      http:
        paths:
        - path: /
          backend:
              serviceName: api-server
              servicePort: 3000