apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sbc-outbound
  name: sbc-outbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbc-outbound
  template:
    metadata:
      labels:
        app: sbc-outbound
    spec:
      containers:
        - env:
            - name: DRACHTIO_HOST
              value: drachtio-sbc
            - name: DRACHTIO_PORT
              value: "9022"
            - name: DRACHTIO_SECRET
              value: cymru
            - name: ENABLE_METRICS
              value: "0"
            - name: JAMBONES_CLUSTER_ID
              value: jb
            - name: JAMBONES_LOGLEVEL
              value: info
            - name: JAMBONES_MYSQL_DATABASE
              value: jambones
            - name: JAMBONES_MYSQL_HOST
              value: mysql
            - name: JAMBONES_MYSQL_PASSWORD
              value: jambones
            - name: JAMBONES_MYSQL_USER
              value: jambones
            - name: JAMBONES_REDIS_HOST
              value: redis
            - name: JAMBONES_REDIS_PORT
              value: "6379"
            - name: JAMBONES_RTPENGINES
              value: rtpengine:22222
            - name: NODE_ENV
              value: production
          image: jambonz/sbc-outbound:latest
          name: sbc-outbound
          resources: {}
      restartPolicy: Always
