apiVersion: v1
kind: Service
metadata:
  labels:
    app: call-router
  name: call-router
spec:
  ports:
    - name: "4000"
      port: 4000
      protocol: UDP
      targetPort: 4000
  selector:
    app: call-router
