apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: jambonzwebapp
      annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
    - host: webapp
      http:
        paths:
        - path: /
          backend:
              serviceName: webapp
              servicePort: 3001